///////////////////////////////////////////////////
// This file is generated by build-interfaces.ts //
///////////////////////////////////////////////////

import {
  LaraJoinPoint,
  registerJoinpointMapper,
  wrapJoinPoint,
  unwrapJoinPoint,
  InsertPosition,
} from "@specs-feup/lara/api/LaraJoinPoint.ts";

type PrivateMapper = {
  "Joinpoint": typeof Joinpoint,
  "App": typeof App,
  "LibMethod": typeof LibMethod,
  "XmlNode": typeof XmlNode,
  "AndroidManifest": typeof AndroidManifest,
  "XmlElement": typeof XmlElement,
  "FileJp": typeof FileJp,
  "NamedType": typeof NamedType,
  "Type": typeof Type,
  "Class": typeof Class,
  "InterfaceType": typeof InterfaceType,
  "Executable": typeof Executable,
  "Method": typeof Method,
  "Constructor": typeof Constructor,
  "AnonymousExec": typeof AnonymousExec,
  "Declaration": typeof Declaration,
  "Catch": typeof Catch,
  "Statement": typeof Statement,
  "CallStatement": typeof CallStatement,
  "Assignment": typeof Assignment,
  "OpAssignment": typeof OpAssignment,
  "Expression": typeof Expression,
  "Annotation": typeof Annotation,
  "Var": typeof Var,
  "FieldAccess": typeof FieldAccess,
  "Literal": typeof Literal,
  "Call": typeof Call,
  "New": typeof New,
  "BinaryExpression": typeof BinaryExpression,
  "UnaryExpression": typeof UnaryExpression,
  "Ternary": typeof Ternary,
  "ArrayAccess": typeof ArrayAccess,
  "This": typeof This,
  "SnippetExpr": typeof SnippetExpr,
  "Return": typeof Return,
  "Comment": typeof Comment,
  "Pragma": typeof Pragma,
  "Assert": typeof Assert,
  "Throw": typeof Throw,
  "Switch": typeof Switch,
  "Case": typeof Case,
  "Continue": typeof Continue,
  "Break": typeof Break,
  "SnippetStmt": typeof SnippetStmt,
  "Reference": typeof Reference,
  "TypeReference": typeof TypeReference,
  "LibClass": typeof LibClass,
  "Field": typeof Field,
  "EnumValue": typeof EnumValue,
  "Body": typeof Body,
  "LocalVariable": typeof LocalVariable,
  "Loop": typeof Loop,
  "If": typeof If,
  "Try": typeof Try,
};

type DefaultAttributeMap = {
  LibMethod: "name",
  XmlElement: "name",
  FileJp: "name",
  NamedType: "name",
  Type: "name",
  Class: "name",
  InterfaceType: "name",
  Executable: "name",
  Method: "name",
  Constructor: "name",
  AnonymousExec: "name",
  Declaration: "name",
  Statement: "kind",
  CallStatement: "kind",
  Assignment: "operator",
  OpAssignment: "operator",
  Var: "name",
  FieldAccess: "name",
  Literal: "value",
  Call: "name",
  New: "name",
  BinaryExpression: "operator",
  UnaryExpression: "operator",
  Return: "kind",
  Comment: "type",
  Pragma: "name",
  Assert: "kind",
  Throw: "kind",
  Switch: "kind",
  Case: "kind",
  Continue: "kind",
  Break: "kind",
  SnippetStmt: "kind",
  Reference: "name",
  TypeReference: "name",
  LibClass: "name",
  Field: "name",
  EnumValue: "name",
  Body: "kind",
  LocalVariable: "name",
  Loop: "type",
  If: "kind",
  Try: "kind",
}

export class Joinpoint extends LaraJoinPoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * An array of the annotations of this node
   */
  get annotations(): Annotation[] { return wrapJoinPoint(this._javaObject.annotations()) }
  /**
   * A string representation of the AST corresponding to this node
   */
  get ast(): string { return wrapJoinPoint(this._javaObject.ast()) }
  /**
   * Alias of attribute 'parent'
   */
  get astParent(): Joinpoint { return wrapJoinPoint(this._javaObject.astParent()) }
  /**
   * The children of this join point, ignoring null nodes
   */
  get children(): Joinpoint[] { return wrapJoinPoint(this._javaObject.children()) }
  /**
   * All descendants of this join point
   */
  get descendants(): Joinpoint[] { return wrapJoinPoint(this._javaObject.descendants()) }
  /**
   * Unique identifier for node
   */
  get id(): string { return wrapJoinPoint(this._javaObject.id()) }
  /**
   * True if this node is considered a block of statements
   */
  get isBlock(): boolean { return wrapJoinPoint(this._javaObject.isBlock()) }
  /**
   * True if this node has the modifier 'final'
   */
  get isFinal(): boolean { return wrapJoinPoint(this._javaObject.isFinal()) }
  /**
   * True if the node is inside a loop header, false otherwise
   */
  get isInsideLoopHeader(): boolean { return wrapJoinPoint(this._javaObject.isInsideLoopHeader()) }
  /**
   * True if this node is considered a statement
   */
  get isStatement(): boolean { return wrapJoinPoint(this._javaObject.isStatement()) }
  /**
   * True if this node has the modifier 'static'
   */
  get isStatic(): boolean { return wrapJoinPoint(this._javaObject.isStatic()) }
  /**
   * Sibling nodes to the left of this node
   */
  get left(): Joinpoint[] { return wrapJoinPoint(this._javaObject.left()) }
  /**
   * An array of modifiers (e.g., final, static) applied to this node. If no modifiers are applied, or if the node does not support modifiers, returns an empty array
   */
  get modifiers(): string[] { return wrapJoinPoint(this._javaObject.modifiers()) }
  /**
   * An array of modifiers (e.g., final, static) applied to this node. If no modifiers are applied, or if the node does not support modifiers, returns an empty array
   */
  set modifiers(value: string[]) { this._javaObject.setModifiers(unwrapJoinPoint(value)); }
  /**
   * Returns the number of children of the node
   */
  get numChildren(): number { return wrapJoinPoint(this._javaObject.numChildren()) }
  /**
   * Returns the parent node in the AST, or undefined if it is the root node
   */
  get parent(): Joinpoint { return wrapJoinPoint(this._javaObject.parent()) }
  /**
   * Sibling nodes to the right of this node
   */
  get right(): Joinpoint[] { return wrapJoinPoint(this._javaObject.right()) }
  /**
   * The root of the tree
   */
  get root(): Joinpoint { return wrapJoinPoint(this._javaObject.root()) }
  /**
   * The scope nodes of this join point
   */
  get scopeNodes(): Joinpoint[] { return wrapJoinPoint(this._javaObject.scopeNodes()) }
  /**
   * Alias for attribute 'code'
   */
  get srcCode(): string { return wrapJoinPoint(this._javaObject.srcCode()) }
  /**
   * Returns the child of the node at the given index
   */
  child(index: number): Joinpoint { return wrapJoinPoint(this._javaObject.child(unwrapJoinPoint(index))); }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  compareNodes(aJoinPoint: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.compareNodes(unwrapJoinPoint(aJoinPoint))); }
  /**
   * Copies the node and returns the copy
   */
  copy(): Joinpoint { return wrapJoinPoint(this._javaObject.copy()); }
  getAncestor(type: string): Joinpoint { return wrapJoinPoint(this._javaObject.getAncestor(unwrapJoinPoint(type))); }
  /**
   * True if this node has the given modifier
   */
  hasModifier(modifier: string): boolean { return wrapJoinPoint(this._javaObject.hasModifier(unwrapJoinPoint(modifier))); }
  insert(position: InsertPosition, code: string): Joinpoint[];
  insert(position: InsertPosition, joinpoint: Joinpoint): Joinpoint[];
  insert(p1: InsertPosition, p2: string | Joinpoint): Joinpoint[] { return wrapJoinPoint(this._javaObject.insert(unwrapJoinPoint(p1), unwrapJoinPoint(p2))); }
  /**
   * Inserts node after the given node
   */
  insertAfter(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts String
   */
  insertAfter(code: string): Joinpoint;
  /**
   * Inserts node after the given node
   */
  insertAfter(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertAfter(unwrapJoinPoint(p1))); }
  /**
   * Inserts node before the given node
   */
  insertBefore(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts String
   */
  insertBefore(code: string): Joinpoint;
  /**
   * Inserts node before the given node
   */
  insertBefore(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertBefore(unwrapJoinPoint(p1))); }
  /**
   * Replaces join point with the given node
   */
  insertReplace(jp: Joinpoint): Joinpoint;
  /**
   * Overload which accepts String
   */
  insertReplace(code: string): Joinpoint;
  /**
   * Replaces join point with the given node
   */
  insertReplace(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertReplace(unwrapJoinPoint(p1))); }
  /**
   * Deletes the node
   */
  remove(): void { return wrapJoinPoint(this._javaObject.remove()); }
  /**
   * Removes an annotation
   */
  removeAnnotation(annotation: Annotation): void { return wrapJoinPoint(this._javaObject.removeAnnotation(unwrapJoinPoint(annotation))); }
  removeModifier(modifier: string): void { return wrapJoinPoint(this._javaObject.removeModifier(unwrapJoinPoint(modifier))); }
  /**
   * Replaces join point with the given node
   */
  replaceWith(jp: Joinpoint): Joinpoint;
  /**
   * Overload which accepts String
   */
  replaceWith(code: string): Joinpoint;
  /**
   * Replaces join point with the given node
   */
  replaceWith(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.replaceWith(unwrapJoinPoint(p1))); }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  same(other: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.same(unwrapJoinPoint(other))); }
  setLine(value: number): void;
  setLine(value: string): void;
  setLine(p1: number | string): void { return wrapJoinPoint(this._javaObject.setLine(unwrapJoinPoint(p1))); }
  setModifiers(modifiers: string[]): void { return wrapJoinPoint(this._javaObject.setModifiers(unwrapJoinPoint(modifiers))); }
}

  /**
   * Root node that represents the application
   */
export class App extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get files(): FileJp[] { return wrapJoinPoint(this._javaObject.files()) }
  get folder(): string { return wrapJoinPoint(this._javaObject.folder()) }
  get manifest(): AndroidManifest { return wrapJoinPoint(this._javaObject.manifest()) }
  mapVersions(name: string, keyType: string, interfaceType: InterfaceType, methodName: string): Class { return wrapJoinPoint(this._javaObject.mapVersions(unwrapJoinPoint(name), unwrapJoinPoint(keyType), unwrapJoinPoint(interfaceType), unwrapJoinPoint(methodName))); }
  newClass(name: string, extend: string, implement: string[]): Class;
  newClass(name: string): Class;
  newClass(p1: string, p2?: string, p3?: string[]): Class { return wrapJoinPoint(this._javaObject.newClass(unwrapJoinPoint(p1), unwrapJoinPoint(p2), unwrapJoinPoint(p3))); }
  newInterface(name: string, extend: string[]): InterfaceType;
  newInterface(name: string): InterfaceType;
  newInterface(p1: string, p2?: string[]): InterfaceType { return wrapJoinPoint(this._javaObject.newInterface(unwrapJoinPoint(p1), unwrapJoinPoint(p2))); }
  showAST(Title: string): string { return wrapJoinPoint(this._javaObject.showAST(unwrapJoinPoint(Title))); }
}

  /**
   * Method of a class that is part of a library included in the classpath
   */
export class LibMethod extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get declarator(): NamedType { return wrapJoinPoint(this._javaObject.declarator()) }
  /**
   * The simple name of the type
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get returnType(): string { return wrapJoinPoint(this._javaObject.returnType()) }
}

export class XmlNode extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get elements(): XmlElement[] { return wrapJoinPoint(this._javaObject.elements()) }
  get text(): string { return wrapJoinPoint(this._javaObject.text()) }
  set text(value: string) { this._javaObject.setText(unwrapJoinPoint(value)); }
  elementsByName(name: string): XmlElement[] { return wrapJoinPoint(this._javaObject.elementsByName(unwrapJoinPoint(name))); }
  setText(text: string): string { return wrapJoinPoint(this._javaObject.setText(unwrapJoinPoint(text))); }
}

export class AndroidManifest extends XmlNode {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get asJson(): string { return wrapJoinPoint(this._javaObject.asJson()) }
}

export class XmlElement extends XmlNode {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * A list of available attributes in this element
   */
  get attributeNames(): string[] { return wrapJoinPoint(this._javaObject.attributeNames()) }
  /**
   * The name (i.e., tag) of this element
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  /**
   * The value associated with the given attribute
   */
  attribute(name: string): string { return wrapJoinPoint(this._javaObject.attribute(unwrapJoinPoint(name))); }
  setAttribute(name: string, value: string): string { return wrapJoinPoint(this._javaObject.setAttribute(unwrapJoinPoint(name), unwrapJoinPoint(value))); }
}

  /**
   * Represents a source-code file
   */
export class FileJp extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get dir(): string { return wrapJoinPoint(this._javaObject.dir()) }
  /**
   * Main class of the file. Java files must have a top level class with the same name as the file.
   */
  get mainClass(): Type { return wrapJoinPoint(this._javaObject.mainClass()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get numClasses(): number { return wrapJoinPoint(this._javaObject.numClasses()) }
  get numInterfaces(): number { return wrapJoinPoint(this._javaObject.numInterfaces()) }
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
  get path(): string { return wrapJoinPoint(this._javaObject.path()) }
  /**
   * Insert a given class inside the target
   */
  addClass(newClass: Class): void { return wrapJoinPoint(this._javaObject.addClass(unwrapJoinPoint(newClass))); }
  addImport(qualifiedName: string): void { return wrapJoinPoint(this._javaObject.addImport(unwrapJoinPoint(qualifiedName))); }
  addInterface(newInterface: InterfaceType): void { return wrapJoinPoint(this._javaObject.addInterface(unwrapJoinPoint(newInterface))); }
  mapVersions(name: string, keyType: string, interfaceType: InterfaceType, methodName: string): Class { return wrapJoinPoint(this._javaObject.mapVersions(unwrapJoinPoint(name), unwrapJoinPoint(keyType), unwrapJoinPoint(interfaceType), unwrapJoinPoint(methodName))); }
  newClass(name: string, extend: string, implement: string[]): Class;
  newClass(name: string): Class;
  newClass(p1: string, p2?: string, p3?: string[]): Class { return wrapJoinPoint(this._javaObject.newClass(unwrapJoinPoint(p1), unwrapJoinPoint(p2), unwrapJoinPoint(p3))); }
  newInterface(name: string, extend: string[]): InterfaceType;
  newInterface(name: string): InterfaceType;
  newInterface(p1: string, p2?: string[]): InterfaceType { return wrapJoinPoint(this._javaObject.newInterface(unwrapJoinPoint(p1), unwrapJoinPoint(p2))); }
  removeInterface(interfaceName: string): InterfaceType { return wrapJoinPoint(this._javaObject.removeInterface(unwrapJoinPoint(interfaceName))); }
}

export class NamedType extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * List of names of interfaces that this type implements
   */
  get interfaces(): string[] { return wrapJoinPoint(this._javaObject.interfaces()) }
  get javadoc(): string { return wrapJoinPoint(this._javaObject.javadoc()) }
  /**
   * The simple name of the type
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  /**
   * Package name of this type
   */
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
  /**
   * The qualified name of this type, includes packages
   */
  get qualifiedName(): string { return wrapJoinPoint(this._javaObject.qualifiedName()) }
  /**
   * Name of the superclass this type extends
   */
  get superClass(): string { return wrapJoinPoint(this._javaObject.superClass()) }
  /**
   * Verify if the type is extends OR implements the given type
   */
  isSubtypeOf(type: string): boolean { return wrapJoinPoint(this._javaObject.isSubtypeOf(unwrapJoinPoint(type))); }
}

  /**
   * Base join point that class, interface and enum extend
   */
export class Type extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * List of names of interfaces that this class implements
   */
  get interfaces(): string[] { return wrapJoinPoint(this._javaObject.interfaces()) }
  /**
   * Returns the interface join points that this class implements
   */
  get interfacesTypes(): InterfaceType[] { return wrapJoinPoint(this._javaObject.interfacesTypes()) }
  get javadoc(): string { return wrapJoinPoint(this._javaObject.javadoc()) }
  /**
   * The simple name of the class
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  /**
   * Package name of this class
   */
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
  /**
   * The qualified name of this class, includes packages
   */
  get qualifiedName(): string { return wrapJoinPoint(this._javaObject.qualifiedName()) }
  /**
   * Name of the superclass this class extends
   */
  get superClass(): string { return wrapJoinPoint(this._javaObject.superClass()) }
  /**
   * The superclass this class extends, or undefined if the class extends java.lang.Object
   */
  get superClassJp(): TypeReference { return wrapJoinPoint(this._javaObject.superClassJp()) }
  /**
   * Insert a given class inside the target
   */
  addClass(newClass: Class): void { return wrapJoinPoint(this._javaObject.addClass(unwrapJoinPoint(newClass))); }
  addImplement(interfaceType: InterfaceType): void { return wrapJoinPoint(this._javaObject.addImplement(unwrapJoinPoint(interfaceType))); }
  addInterface(newInterface: InterfaceType): void { return wrapJoinPoint(this._javaObject.addInterface(unwrapJoinPoint(newInterface))); }
  insertCode(code: string): void { return wrapJoinPoint(this._javaObject.insertCode(unwrapJoinPoint(code))); }
  insertMethod(code: string): void { return wrapJoinPoint(this._javaObject.insertMethod(unwrapJoinPoint(code))); }
  /**
   * Verify if the type is extends OR implements the given type
   */
  isSubtypeOf(type: string): boolean { return wrapJoinPoint(this._javaObject.isSubtypeOf(unwrapJoinPoint(type))); }
  newField(modifiers: string[], type: string, name: string, defaultValue?: string): Field;
  newField(modifiers: string[], type: string, name: string): Field;
  newField(p1: string[], p2: string, p3: string, p4?: string): Field { return wrapJoinPoint(this._javaObject.newField(unwrapJoinPoint(p1), unwrapJoinPoint(p2), unwrapJoinPoint(p3), unwrapJoinPoint(p4))); }
  /**
   * Add a new method inside the class
   */
  newMethod(modifiers: string[], returnType: string, name: string, paramLeft: string[], paramRight: string[], code: string): Method;
  /**
   * Overload which accepts 4 parameters (code is empty string)
   */
  newMethod(modifiers: string[], returnType: string, name: string, paramLeft: string[], paramRight: string[]): Method;
  /**
   * Add a new method inside the class
   */
  newMethod(p1: string[], p2: string, p3: string, p4: string[], p5: string[], p6?: string): Method { return wrapJoinPoint(this._javaObject.newMethod(unwrapJoinPoint(p1), unwrapJoinPoint(p2), unwrapJoinPoint(p3), unwrapJoinPoint(p4), unwrapJoinPoint(p5), unwrapJoinPoint(p6))); }
  removeInterface(interfaceName: string): InterfaceType { return wrapJoinPoint(this._javaObject.removeInterface(unwrapJoinPoint(interfaceName))); }
}

  /**
   * Join point representation of a class
   */
export class Class extends Type {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get isTopLevel(): boolean { return wrapJoinPoint(this._javaObject.isTopLevel()) }
  extractInterface(name: string, packageName: string = "", method: Method, associate: boolean = false, newFile: boolean): InterfaceType { return wrapJoinPoint(this._javaObject.extractInterface(unwrapJoinPoint(name), unwrapJoinPoint(packageName), unwrapJoinPoint(method), unwrapJoinPoint(associate), unwrapJoinPoint(newFile))); }
  insertStatic(code: string): void { return wrapJoinPoint(this._javaObject.insertStatic(unwrapJoinPoint(code))); }
  mapVersions(name: string, keyType: string, interfaceType: InterfaceType, methodName: string): Class { return wrapJoinPoint(this._javaObject.mapVersions(unwrapJoinPoint(name), unwrapJoinPoint(keyType), unwrapJoinPoint(interfaceType), unwrapJoinPoint(methodName))); }
  newConstructor(modifiers: string[] = ['public'], paramLeft: string[] = [], paramRight: string[] = []): Constructor { return wrapJoinPoint(this._javaObject.newConstructor(unwrapJoinPoint(modifiers), unwrapJoinPoint(paramLeft), unwrapJoinPoint(paramRight))); }
  newFunctionalClass(interfaceMethod: Method, generatorMethod: Method): Method { return wrapJoinPoint(this._javaObject.newFunctionalClass(unwrapJoinPoint(interfaceMethod), unwrapJoinPoint(generatorMethod))); }
}

export class InterfaceType extends Type {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
}

export class Executable extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get body(): Body { return wrapJoinPoint(this._javaObject.body()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  set name(value: string) { this._javaObject.setName(unwrapJoinPoint(value)); }
  get params(): Declaration[] { return wrapJoinPoint(this._javaObject.params()) }
  get returnRef(): TypeReference { return wrapJoinPoint(this._javaObject.returnRef()) }
  get returnType(): string { return wrapJoinPoint(this._javaObject.returnType()) }
  /**
   * Sets the name of this executable, returns the previous name
   */
  setName(name: string): string { return wrapJoinPoint(this._javaObject.setName(unwrapJoinPoint(name))); }
}

export class Method extends Executable {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get declarator(): string { return wrapJoinPoint(this._javaObject.declarator()) }
  get privacy(): string { return wrapJoinPoint(this._javaObject.privacy()) }
  set privacy(value: string) { this._javaObject.setPrivacy(unwrapJoinPoint(value)); }
  get toQualifiedReference(): string { return wrapJoinPoint(this._javaObject.toQualifiedReference()) }
  get toReference(): string { return wrapJoinPoint(this._javaObject.toReference()) }
  addComment(comment: string): void { return wrapJoinPoint(this._javaObject.addComment(unwrapJoinPoint(comment))); }
  addParameter(type: string, name: string): void { return wrapJoinPoint(this._javaObject.addParameter(unwrapJoinPoint(type), unwrapJoinPoint(name))); }
  clone(newName: string): Method { return wrapJoinPoint(this._javaObject.clone(unwrapJoinPoint(newName))); }
  createAdapter(adaptMethod: Method, name: string): Class { return wrapJoinPoint(this._javaObject.createAdapter(unwrapJoinPoint(adaptMethod), unwrapJoinPoint(name))); }
  isOverriding(method: Method): boolean { return wrapJoinPoint(this._javaObject.isOverriding(unwrapJoinPoint(method))); }
  setPrivacy(privacy: string): void { return wrapJoinPoint(this._javaObject.setPrivacy(unwrapJoinPoint(privacy))); }
}

export class Constructor extends Executable {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get declarator(): string { return wrapJoinPoint(this._javaObject.declarator()) }
}

export class AnonymousExec extends Executable {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
}

export class Declaration extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get completeType(): string { return wrapJoinPoint(this._javaObject.completeType()) }
  get init(): Expression { return wrapJoinPoint(this._javaObject.init()) }
  set init(value: Expression) { this._javaObject.setInit(unwrapJoinPoint(value)); }
  get isArray(): boolean { return wrapJoinPoint(this._javaObject.isArray()) }
  get isPrimitive(): boolean { return wrapJoinPoint(this._javaObject.isPrimitive()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get type(): string { return wrapJoinPoint(this._javaObject.type()) }
  get typeReference(): TypeReference { return wrapJoinPoint(this._javaObject.typeReference()) }
  setInit(value: Expression): void { return wrapJoinPoint(this._javaObject.setInit(unwrapJoinPoint(value))); }
}

export class Catch extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get body(): Body { return wrapJoinPoint(this._javaObject.body()) }
}

export class Statement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  get endLine(): number { return wrapJoinPoint(this._javaObject.endLine()) }
  get kind(): string { return wrapJoinPoint(this._javaObject.kind()) }
}

export class CallStatement extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  get call(): Call { return wrapJoinPoint(this._javaObject.call()) }
}

export class Assignment extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "operator",
  };
  get lhs(): Expression { return wrapJoinPoint(this._javaObject.lhs()) }
  set lhs(value: Expression) { this._javaObject.setLhs(unwrapJoinPoint(value)); }
  get operator(): string { return wrapJoinPoint(this._javaObject.operator()) }
  get rhs(): Expression { return wrapJoinPoint(this._javaObject.rhs()) }
  set rhs(value: Expression) { this._javaObject.setRhs(unwrapJoinPoint(value)); }
  setLhs(lhs: Expression): void { return wrapJoinPoint(this._javaObject.setLhs(unwrapJoinPoint(lhs))); }
  setRhs(rhs: Expression): void { return wrapJoinPoint(this._javaObject.setRhs(unwrapJoinPoint(rhs))); }
}

export class OpAssignment extends Assignment {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "operator",
  };
  setOperator(operator: string): void { return wrapJoinPoint(this._javaObject.setOperator(unwrapJoinPoint(operator))); }
}

export class Expression extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get kind(): string { return wrapJoinPoint(this._javaObject.kind()) }
  get qualifiedType(): string { return wrapJoinPoint(this._javaObject.qualifiedType()) }
  get test(): number { return wrapJoinPoint(this._javaObject.test()) }
  set test(value: Expression | number) { this._javaObject.setTest(unwrapJoinPoint(value)); }
  get type(): string { return wrapJoinPoint(this._javaObject.type()) }
  get typeReference(): TypeReference { return wrapJoinPoint(this._javaObject.typeReference()) }
  extract(varName: string, location: Statement, position: string): void { return wrapJoinPoint(this._javaObject.extract(unwrapJoinPoint(varName), unwrapJoinPoint(location), unwrapJoinPoint(position))); }
  setTest(test: Expression): void;
  setTest(test: number): void;
  setTest(p1: Expression | number): void { return wrapJoinPoint(this._javaObject.setTest(unwrapJoinPoint(p1))); }
}

export class Annotation extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class Var extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get declaration(): Joinpoint { return wrapJoinPoint(this._javaObject.declaration()) }
  /**
   * Equivalent to the global attribute 'isInsideLoopHeader'
   */
  get inLoopHeader(): boolean { return wrapJoinPoint(this._javaObject.inLoopHeader()) }
  get isArray(): boolean { return wrapJoinPoint(this._javaObject.isArray()) }
  get isField(): boolean { return wrapJoinPoint(this._javaObject.isField()) }
  get isPrimitive(): boolean { return wrapJoinPoint(this._javaObject.isPrimitive()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get reference(): RefType { return wrapJoinPoint(this._javaObject.reference()) }
  /**
   * The chain of references of this variable (e.g., this.field)
   */
  get referenceChain(): Joinpoint[] { return wrapJoinPoint(this._javaObject.referenceChain()) }
}

export class FieldAccess extends Var {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * The base expression of this fieldAccess. E.g., for the field access a.b.c, returns the expression representing a.b
   */
  get base(): Expression { return wrapJoinPoint(this._javaObject.base()) }
}

export class Literal extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "value",
  };
  get value(): string { return wrapJoinPoint(this._javaObject.value()) }
  set value(value: string) { this._javaObject.setValue(unwrapJoinPoint(value)); }
  setValue(value: string): void { return wrapJoinPoint(this._javaObject.setValue(unwrapJoinPoint(value))); }
}

export class Call extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get arguments(): Expression[] { return wrapJoinPoint(this._javaObject.arguments()) }
  set arguments(value: Expression[]) { this._javaObject.setArguments(unwrapJoinPoint(value)); }
  get decl(): Method { return wrapJoinPoint(this._javaObject.decl()) }
  get declarator(): string { return wrapJoinPoint(this._javaObject.declarator()) }
  get executable(): string { return wrapJoinPoint(this._javaObject.executable()) }
  set executable(value: Method) { this._javaObject.setExecutable(unwrapJoinPoint(value)); }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get qualifiedDecl(): string { return wrapJoinPoint(this._javaObject.qualifiedDecl()) }
  get returnType(): string { return wrapJoinPoint(this._javaObject.returnType()) }
  get returnTypeJp(): TypeReference { return wrapJoinPoint(this._javaObject.returnTypeJp()) }
  get simpleDecl(): string { return wrapJoinPoint(this._javaObject.simpleDecl()) }
  get target(): string { return wrapJoinPoint(this._javaObject.target()) }
  set target(value: Expression | string) { this._javaObject.setTarget(unwrapJoinPoint(value)); }
  get targetType(): Type { return wrapJoinPoint(this._javaObject.targetType()) }
  clone(location: Statement, position: string): Call { return wrapJoinPoint(this._javaObject.clone(unwrapJoinPoint(location), unwrapJoinPoint(position))); }
  setArgument(newArgument: Expression, index: number): void { return wrapJoinPoint(this._javaObject.setArgument(unwrapJoinPoint(newArgument), unwrapJoinPoint(index))); }
  setArguments(newArguments: Expression[]): void { return wrapJoinPoint(this._javaObject.setArguments(unwrapJoinPoint(newArguments))); }
  setExecutable(executable: Method): Call { return wrapJoinPoint(this._javaObject.setExecutable(unwrapJoinPoint(executable))); }
  setTarget(target?: Expression): Call;
  setTarget(target?: string): Call;
  setTarget(p1?: Expression | string): Call { return wrapJoinPoint(this._javaObject.setTarget(unwrapJoinPoint(p1))); }
}

export class New extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get arguments(): Expression[] { return wrapJoinPoint(this._javaObject.arguments()) }
  set arguments(value: Expression[]) { this._javaObject.setArguments(unwrapJoinPoint(value)); }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  setArguments(newArguments: Expression[]): void { return wrapJoinPoint(this._javaObject.setArguments(unwrapJoinPoint(newArguments))); }
}

export class BinaryExpression extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "operator",
  };
  get lhs(): Expression { return wrapJoinPoint(this._javaObject.lhs()) }
  get operands(): Expression[] { return wrapJoinPoint(this._javaObject.operands()) }
  get operator(): string { return wrapJoinPoint(this._javaObject.operator()) }
  set operator(value: string) { this._javaObject.setOperator(unwrapJoinPoint(value)); }
  get rhs(): Expression { return wrapJoinPoint(this._javaObject.rhs()) }
  setOperator(operator: string): void { return wrapJoinPoint(this._javaObject.setOperator(unwrapJoinPoint(operator))); }
}

export class UnaryExpression extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "operator",
  };
  get operand(): Expression { return wrapJoinPoint(this._javaObject.operand()) }
  get operator(): string { return wrapJoinPoint(this._javaObject.operator()) }
  set operator(value: string) { this._javaObject.setOperator(unwrapJoinPoint(value)); }
  /**
   * Sets the operator of the unary expression. To distinguish between postfix and prefix operator, add an underscore signalling the place of the variable (e.g., _++ for postfix incremment). If no underscore is specified, postfix is assumed.
   */
  setOperator(operator: string): void { return wrapJoinPoint(this._javaObject.setOperator(unwrapJoinPoint(operator))); }
}

export class Ternary extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * Alias for attribute 'condition'
   */
  get cond(): Expression { return wrapJoinPoint(this._javaObject.cond()) }
  /**
   * The condition of the ternary expression
   */
  get condition(): Expression { return wrapJoinPoint(this._javaObject.condition()) }
  get else(): Expression { return wrapJoinPoint(this._javaObject._else()) }
  get then(): Expression { return wrapJoinPoint(this._javaObject.then()) }
}

export class ArrayAccess extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get reference(): RefType { return wrapJoinPoint(this._javaObject.reference()) }
}

export class This extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class SnippetExpr extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  setLine(value: number | string): void;
  setLine(line: number): void;
  setLine(p1: number | string): void { return wrapJoinPoint(this._javaObject.setLine(unwrapJoinPoint(p1))); }
}

export class Return extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
}

export class Comment extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "type",
  };
  get content(): string { return wrapJoinPoint(this._javaObject.content()) }
  get type(): CommentType { return wrapJoinPoint(this._javaObject.type()) }
}

export class Pragma extends Comment {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

export class Assert extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
}

export class Throw extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
}

export class Switch extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  get cases(): Case[] { return wrapJoinPoint(this._javaObject.cases()) }
}

export class Case extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  /**
   * The expression associated with this case, of undefined if it is the default case
   */
  get expr(): Expression { return wrapJoinPoint(this._javaObject.expr()) }
  /**
   * True if this is the default case, false otherwise
   */
  get isDefault(): boolean { return wrapJoinPoint(this._javaObject.isDefault()) }
  /**
   * The statements of this case
   */
  get stmts(): Statement[] { return wrapJoinPoint(this._javaObject.stmts()) }
}

export class Continue extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
}

export class Break extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
}

export class SnippetStmt extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  setLine(value: number | string): void;
  setLine(line: number): void;
  setLine(p1: number | string): void { return wrapJoinPoint(this._javaObject.setLine(unwrapJoinPoint(p1))); }
}

  /**
   * Points to a named program element reference
   */
export class Reference extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * The element that is being referenced
   */
  get declaration(): Joinpoint { return wrapJoinPoint(this._javaObject.declaration()) }
  /**
   * Name of the element of the reference
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  /**
   * Type of the element of the reference
   */
  get type(): string { return wrapJoinPoint(this._javaObject.type()) }
}

  /**
   * Reference to a type
   */
export class TypeReference extends Reference {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * True if this is a reference to an array type, false otherwise
   */
  get isArray(): boolean { return wrapJoinPoint(this._javaObject.isArray()) }
  /**
   * True if this is a reference to a boolean type, primitive or class (i.e., boolean, Boolean)
   */
  get isBoolean(): boolean { return wrapJoinPoint(this._javaObject.isBoolean()) }
  /**
   * True if this is a reference to a numeric type, primitive or class (i.e., byte, Byte, char, Character, short, Short, int, Integer, long, Long, float, Float, double and Double)
   */
  get isNumeric(): boolean { return wrapJoinPoint(this._javaObject.isNumeric()) }
  /**
   * True if this is a reference to a primitive type, false otherwise
   */
  get isPrimitive(): boolean { return wrapJoinPoint(this._javaObject.isPrimitive()) }
  /**
   * Package name of this type
   */
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
  /**
   * The package name of this type as an array, where each element is a part of the package
   */
  get packageNames(): string[] { return wrapJoinPoint(this._javaObject.packageNames()) }
  /**
   * Fully qualified name of the type
   */
  get qualifiedName(): string { return wrapJoinPoint(this._javaObject.qualifiedName()) }
}

  /**
   * Class that is part of a library, included in the classpath
   */
export class LibClass extends NamedType {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
}

export class Field extends Declaration {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get declarator(): string { return wrapJoinPoint(this._javaObject.declarator()) }
  get staticAccess(): string { return wrapJoinPoint(this._javaObject.staticAccess()) }
}

export class EnumValue extends Field {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
}

export class Body extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  /**
   * The last statement of the body, or undefined if it has no statements
   */
  get lastStmt(): Statement { return wrapJoinPoint(this._javaObject.lastStmt()) }
  insertBegin(code: string): void;
  insertBegin(statement: Statement): void;
  insertBegin(p1: string | Statement): void { return wrapJoinPoint(this._javaObject.insertBegin(unwrapJoinPoint(p1))); }
}

export class LocalVariable extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  get completeType(): string { return wrapJoinPoint(this._javaObject.completeType()) }
  /**
   * Initialization of this variable, if present, or undefined of unintialized
   */
  get init(): Expression { return wrapJoinPoint(this._javaObject.init()) }
  /**
   * Initialization of this variable, if present, or undefined of unintialized
   */
  set init(value: Expression) { this._javaObject.setInit(unwrapJoinPoint(value)); }
  get isArray(): boolean { return wrapJoinPoint(this._javaObject.isArray()) }
  get isPrimitive(): boolean { return wrapJoinPoint(this._javaObject.isPrimitive()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get type(): string { return wrapJoinPoint(this._javaObject.type()) }
  get typeReference(): TypeReference { return wrapJoinPoint(this._javaObject.typeReference()) }
  setInit(init: Expression): void { return wrapJoinPoint(this._javaObject.setInit(unwrapJoinPoint(init))); }
}

export class Loop extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "type",
  };
  get cond(): Expression { return wrapJoinPoint(this._javaObject.cond()) }
  get controlVar(): string { return wrapJoinPoint(this._javaObject.controlVar()) }
  get isInnermost(): boolean { return wrapJoinPoint(this._javaObject.isInnermost()) }
  get isOutermost(): boolean { return wrapJoinPoint(this._javaObject.isOutermost()) }
  get nestedLevel(): number { return wrapJoinPoint(this._javaObject.nestedLevel()) }
  get rank(): string { return wrapJoinPoint(this._javaObject.rank()) }
  get type(): LoopType { return wrapJoinPoint(this._javaObject.type()) }
  interchange(loop2: Loop): void { return wrapJoinPoint(this._javaObject.interchange(unwrapJoinPoint(loop2))); }
  tile(tileName: string, block: string, unique: boolean, around?: Joinpoint): Field;
  tile(block: number): void;
  tile(p1?: string | number, p2?: string, p3?: boolean, p4?: Joinpoint): Field | void { return wrapJoinPoint(this._javaObject.tile(unwrapJoinPoint(p1), unwrapJoinPoint(p2), unwrapJoinPoint(p3), unwrapJoinPoint(p4))); }
}

export class If extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  get cond(): Expression { return wrapJoinPoint(this._javaObject.cond()) }
  get else(): Body { return wrapJoinPoint(this._javaObject._else()) }
  get rank(): string { return wrapJoinPoint(this._javaObject.rank()) }
  get then(): Body { return wrapJoinPoint(this._javaObject.then()) }
}

export class Try extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "kind",
  };
  get body(): Body { return wrapJoinPoint(this._javaObject.body()) }
  get catches(): Catch[] { return wrapJoinPoint(this._javaObject.catches()) }
}

/**
 * This is supposed to be an enum, but Node.js v25 does bot support TS' enums, only erasable-syntax.
 * Revert to an enum when Node.js supports it, or when we move to a different engine that supports it.
 * This and the "type" declaration below.
 */
export const LoopType = {
  for: "for",
  foreach: "foreach",
  while: "while",
  doWhile: "doWhile",
} as const;
export type LoopType = typeof LoopType[keyof typeof LoopType];

/**
 * This is supposed to be an enum, but Node.js v25 does bot support TS' enums, only erasable-syntax.
 * Revert to an enum when Node.js supports it, or when we move to a different engine that supports it.
 * This and the "type" declaration below.
 */
export const CommentType = {
  file: "file",
  inline: "inline",
  block: "block",
  javadoc: "javadoc",
  pragma: "pragma",
} as const;
export type CommentType = typeof CommentType[keyof typeof CommentType];

/**
 * This is supposed to be an enum, but Node.js v25 does bot support TS' enums, only erasable-syntax.
 * Revert to an enum when Node.js supports it, or when we move to a different engine that supports it.
 * This and the "type" declaration below.
 */
export const RefType = {
  read: "read",
  write: "write",
  readwrite: "readwrite",
  decl: "decl",
} as const;
export type RefType = typeof RefType[keyof typeof RefType];

const JoinpointMapper = {
  joinpoint: Joinpoint,
  app: App,
  libMethod: LibMethod,
  xmlNode: XmlNode,
  androidManifest: AndroidManifest,
  xmlElement: XmlElement,
  file: FileJp,
  NamedType: NamedType,
  type: Type,
  class: Class,
  interfaceType: InterfaceType,
  executable: Executable,
  method: Method,
  constructor: Constructor,
  anonymousExec: AnonymousExec,
  declaration: Declaration,
  catch: Catch,
  statement: Statement,
  callStatement: CallStatement,
  assignment: Assignment,
  opAssignment: OpAssignment,
  expression: Expression,
  annotation: Annotation,
  var: Var,
  fieldAccess: FieldAccess,
  literal: Literal,
  call: Call,
  new: New,
  binaryExpression: BinaryExpression,
  unaryExpression: UnaryExpression,
  ternary: Ternary,
  arrayAccess: ArrayAccess,
  this: This,
  snippetExpr: SnippetExpr,
  return: Return,
  comment: Comment,
  pragma: Pragma,
  assert: Assert,
  throw: Throw,
  switch: Switch,
  case: Case,
  continue: Continue,
  break: Break,
  snippetStmt: SnippetStmt,
  reference: Reference,
  typeReference: TypeReference,
  libClass: LibClass,
  field: Field,
  enumValue: EnumValue,
  body: Body,
  localVariable: LocalVariable,
  loop: Loop,
  if: If,
  try: Try,
};

let registered = false;
if (!registered) {
  registerJoinpointMapper(JoinpointMapper);
  registered = true;
}

